aws-samples/simple-lex-kendra-jp

lib/simple-lexv2-stack.ts
package-lock.json
package.json

cdk deploy 時に ChildDirected 未指定のエラーが出ました。以前は出なかったと思うのですが...
一旦こちらの修正で治りました。

fix childDirected => ChildDirected

---

guide/03_DEPLOY_KENDRA.md
lambda/query.ts
lambda/sync-custom-data-source.ts
lib/simple-kendra-stack.ts
web-kendra/src/components/TypeDocument.tsx
web-lexv2/src/components/kendra/Documents.tsx

add custom resource

---

guide/03_DEPLOY_KENDRA.md
guide/04_DEPLOY_LEXV2.md
web-lexv2/src/components/kendra/Documents.tsx

https://github.com/aws-samples/simple-lex-kendra-jp/issues/6

手元で Frontend を動かす手順の追加

---

docs/01_PRE_REQUIREMENT.md
docs/02_SETUP_CDK.md
docs/03_DEPLOY_KENDRA.md
docs/04_DEPLOY_LEXV2.md
package-lock.json
package.json

Workspace 対応

---

web-kendra/src/components/HighlightText.tsx
web-kendra/src/components/TypeAnswer.tsx
web-kendra/src/components/TypeDocument.tsx
web-kendra/src/components/TypeQuestionAnswer.tsx
web-lexv2/src/App.tsx
web-lexv2/src/components/KendraContent.tsx
web-lexv2/src/components/Lex.tsx
web-lexv2/src/components/kendra/Answer.tsx
web-lexv2/src/components/kendra/Documents.tsx
web-lexv2/src/components/kendra/QuestionAnswer.tsx

Component分割

---

cdk/bin/simple-lex-kendra-jp.ts
cdk/lib/simple-lexv2-stack.ts
cdk/package.json
package-lock.json
package.json

add initial response

---

cdk/bin/simple-lex-kendra-jp.ts
docs/02_SETUP_CDK.md
docs/03_DEPLOY_KENDRA.md
docs/04_DEPLOY_LEXV2.md
docs/05_TECH_KNOWLEDGE.md

Kendra 東京リージョン対応

---

cdk/custom-resources/data-source.js
cdk/lib/simple-kendra-stack.ts
docs/03_DEPLOY_KENDRA.md

Web Crawler の追加

---

cdk/lib/simple-kendra-stack.ts
cdk/lib/simple-lexv2-stack.ts

Lambda の Runtime を指定

---

cdk/bin/simple-lex-kendra-jp.ts
cdk/custom-resources/data-source.js
cdk/custom-resources/faq.js
cdk/lib/constructs/common-web-acl.ts
cdk/lib/constructs/index.ts
cdk/lib/simple-kendra-stack.ts
cdk/lib/simple-lexv2-stack.ts
cdk/lib/web-acl-stack.ts
cdk/package.json
package-lock.json

cdk-nag の適用

---

cdk/cdk.json

remove disableCloudWatchRole: true

---

.github/workflows/node.js.yml
cdk/lib/simple-lexv2-stack.ts

fixes #45 
cdk-nagのエラー解消  
※フロントエンドデプロイ方法修正時の修正漏れ対応

Fix nag error

---

cdk/lib/constructs/common-web-acl.ts

WebACLにIPv6のIPsetを追加

---

README.md
docs/06_TECH_KNOWLEDGE.md

リンクの修正とブログのリンク追加

---

web-kendra-auth/src/lib/useLoginUser.ts

fix authenticatedUser info

---

.gitignore
cdk/custom-resources/package-lock.json
cdk/custom-resources/package.json
cdk/lambda/package-lock.json
cdk/lambda/package.json
cdk/package.json
package-lock.json
package.json
web-kendra-auth/package.json
web-kendra/package.json
web-lexv2/package.json

package.json の name を変更

---

web-kendra-auth/src/components/TypeDocument.tsx
web-kendra/src/components/TypeDocument.tsx

S3のファイル名に日本語や半角スペースが含まれている場合にダウンロードエラーになる件を修正

---

web-kendra/src/hooks/useS3Downloader.ts

RAGチャットで日本語ファイルダウンロードエラーが発生する

---

cdk/cdk.json
cdk/lib/constructs/auth.ts
cdk/lib/constructs/web.ts
cdk/lib/simple-kendra-stack.ts
docs/03_DEPLOY_KENDRA.md
web-kendra/src/App.tsx

By default, this application provides a self-signup feature. There is a security concern as anyone can signup and use this application.
I added the parameter `selfSignUpEnabled` to disable this feature.

Add parameter to disable signup

---

cdk/lambda/retrieve.ts

RetrieveCommand の修正
